### ISSUE TITLE
Prefixing protected/private with underscores

### ISSUE THREAD

**Issue by pedzed** [tres-framework/conventions#5]
Should we prefix properties and methods with underscores? The benefit of this is that it makes the visibility clear:
- With underscore, it's not public.
- Without underscore, it must be public.

Examples:

``` php
class UnderscorePrefixExample {

    public $underscore = true;

    protected $_amount = 0;

    private $_exampleProperty = [];

    public function incrementAmountByN($n){
        $this->_amount = $this->_amount + $n;
    }

    protected function _exampleMethod(){
        $this->_exampleProperty[] = [
            'example',
        ];
    }

}
```

Relevant: https://stackoverflow.com/questions/12013631/protected-properties-prefixed-with-underscores

newfurniturey says:

> I, personally, am also one who uses that naming convention. Prefixing anything that is protected or private with an underscore, be it a variable or a function, lets myself and any other programmer who I regularly work with know that that variable is global and will not be accessible outside of the current class/context.

Wideshanks says:

> By way of comparison, Python doesn't have private/public by design and uses underscores to communicate the distinction. See this section of PEP 8:
> 
> http://www.python.org/dev/peps/pep-0008/#designing-for-inheritance

I like to follow conventions which helps programmers from other languages understand it as easy as possible.

I brought this issue up because I see more people moving to the non-prefixed style. I see two reasons why:
- Programmers prefer looking at `$this->privateMethod()` rather than `$this->_privateMethod()`.
- Programmers are lazy.

If it's the second, then in the end you will probably waste more time because you have to check if something is in fact public, protected or private.

**Comment by julianrichen** [comment]
I personally like prefixing private and protected vars/methods with an underscore. It's easy, takes less than a quarter of a second more to type and makes things clear.
